### PR TITLE
Add Ocean & Sea Ice Data

### PR DESCRIPTION
**Pull request by bradyrx**
@lukelbd, this PR will add a few datasets for the ocean. Note that I am just pulling data from `MPAS-Analysis`, which is a diagnostics package we use to validate the MPAS model over at Los Alamos. Here's a table of the already processed observations: https://mpas-analysis.readthedocs.io/en/master/observations.html

I have them on a drive on a cluster at LANL. So I can just handle the sea ice as well since they have that too. We'll have to do land/atmosphere by hand.

Currently added:
* Sea surface temperature
* Mixed layer depth
* Sea surface salinity

To add (ocean):
* SSH
* A SOSE field for south polar projection
* SeaWIFS
* Some other BGC climatology
* Surface currents

To add (sea ice):
* Ice concentration
* Ice area
* IceSat thickness

### CODE REVIEW

**Comment by lukelbd** [comment]
Awesome, thanks!

**Comment by bradyrx** [comment]
@lukelbd , I'll add the rest of ocean/sea ice in future PRs when I have time.

**Comment by lukelbd** [comment]
Np. Will have time to add stuff this weekend myself.

Also trying to understand how this works, so did I have to approve your merge or could you have done it yourself? We're both collaborators/have push access, so is this just a workflow convention where we approve each other's merges so we are forced to see the changes?

**Comment by bradyrx** [comment]
I could have done it myself. I have no hard hooks on this, since it's just us two and not a package. I could make it so that it has to be approved by one of us, but we're just adding data and light notebook stuff. I'm doing the PR thing so that we don't just merge stuff into master at will. Mainly so that we are forced to see what's going on. Secondly so things don't break (although there won't be much to break)

**Pull request merged**
