### PR TITLE
Starting point for loading and comparing "bad vs. good" colormaps

### PR DESCRIPTION
**Pull request by lukelbd**
Added a notebook that visualizes examples of "bad" colormaps with `cmap_breakdown`. Perhaps it should be merged into your notebook, or maybe this can be a "reference" notebook that we use in our presentation (and give them access to), and a second notebook that they can use to design/visualize their own maps.

The`cmaps.py` module re-registers some bad rainbowy maps (dug into the source code) and adds a little function that infers colormap data from long, thin PNG screenshots of colorbars saved in the `cmaps` folder. So if you come across any particularly janky colormaps while reading papers, feel free to add them!

### CODE REVIEW

**Comment by bradyrx** [comment]
Nice start. Those are some ugly looking color maps. You should definitely step through those breakdown charts in the presentation so folks know what a good colormap looks like.

Just let me know when this is ready to merge and I'll approve.

**Comment by bradyrx** [comment]
The updates are great @lukelbd . Only comment is that the analysis plots are a little dense. I.e., theres a lot of them.

Screen Shot 2019-07-24 at 10 22 51 AM

E.g., we probably don't need RGB here? I imagine linear luminance is the most important part here.

**Comment by lukelbd** [comment]
That's true. RGB is useful when looking at "bad" colormaps to see how they were designed -- usually with linear transformations in RGB-space -- but not so useful when looking at "good" colormaps.

I added an `rgb` keyword arg to `show_channels`, that toggles the RGB row on and off (`show_channels` is the new name for `breakdown_cmap`, to make it match the name of the other demo functions and so that the name no longer implies it has to be used with a single colormap). And I updated the notebook examples, e.g.:

Screen Shot 2019-07-24 at 2 10 01 PM

Also note the [documentation examples](https://proplot.readthedocs.io/en/latest/quickstart5.html#perceptually-uniform-colormaps) are updated with this new kind of breakdown plot.

**Comment by bradyrx** [comment]
Awesome. This looks good to go. Can I merge @lukelbd? Also, those cmaps lifted from publications are horrendous.

**Review by bradyrx — APPROVED** [review]

**Comment by lukelbd** [comment]
Yep with those last commits it's ready to merge. You're welcome to add maps if you want; just take a screenshot of any colorbar you come across and put it in the "cmaps" folder. The "sources" folder includes maps from some other data viz tools we can potentially use.

**Pull request merged**
